apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-parking
  name: postgres-parking
spec:
  replicas: 1

  selector:
    matchLabels:
      io.kompose.service: postgres-parking
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-parking
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: Parking
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: test
        image: postgres:latest
        imagePullPolicy: ""
        name: postgres-parking
        ports:
        - containerPort: 5432
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
